#  Template Java Gradle build

#  This template allows you to test and build your Java project with Gradle.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: appropriate project structure should exist in the repository.

image: gradle:6.7.0

pipelines:
  branches:
    main:
      - step:
          name: Build and Test
          caches:
            - gradle
          script:
            - gradle bootWar
            - scp build/libs/yb.war tuditaiwan@test.tudihis.cn:/data/wwwroot/default/yb.war
